# FilterLib template config
# This library was made by BowFun for Bow Network.
# Due to user safety, you must make your own regex filters, except for links and swear words.
# These are used for examples.

# What is FilterLib?
# FilterLib is a standard text filtering library. This allows for a standard ruleset for text filtering.
# This is not a plugin, but a library used by a plugin you installed on your server.

# Category names have no impact on filtering.
# Higher up categories have greater priority for filtering.
# Also, not all features are guaranteed to work. All features have to be implemented by the plugin developer that uses FilterLib.
swear_words:
  # All regex is processed case-insensitive.
  # Use 2 backslashes instead of 1 to escape characters correctly for YAML. You will get an error if you don't.
  # More info on the double-escape thing above: https://www.reddit.com/r/learnprogramming/comments/13bb5pa
  regex: "\\b(?:\\w*fuck|\\w*bitch|\\w*shit)\\w*\\b"
  # Commands use %player% for player names.
  command: "say %player% said a swear word!"
  # This permission will allow your message to go through regardless of the contents.
  bypass_permission: "filters.bypass.swear"

links:
  regex: "\\b\\S+\\.[a-zA-Z]{2,}\\b"
  command: "say %player% posted a link!"
  bypass_permission: "filters.bypass.links"